Repository the-hacking-team/happy-minute, pull requests merged in 2020-09, with the labels that each got.

#12 First improvement for DEVISE forms
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/main.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
Labels: enhancement

#14 Mailer using IONOS SMTP (contact@happy-minute.com)
  Gemfile
  Gemfile.lock
  app/mailers/owner_mailer.rb
  app/models/owner.rb
  app/views/owner_mailer/welcome_email.html.erb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  test/mailers/owner_mailer_test.rb
  test/mailers/previews/owner_mailer_preview.rb
Labels: enhancement

#29 Business controller
  app/controllers/businesses_controller.rb
  app/views/businesses/destroy.html.erb
  app/views/businesses/index.html.erb
  app/views/businesses/new.html.erb
  app/views/businesses/show.html.erb
  app/views/businesses/update.html.erb
  app/views/owners/show.html.erb
  config/routes.rb
  db/schema.rb
Labels: enhancement

#32 Front for Item (show, new, edit, index)
  app/views/items/_form.html.erb
  app/views/items/_header.html.erb
  app/views/items/_item.html.erb
  app/views/items/edit.html.erb
  app/views/items/index.html.erb
  app/views/items/new.html.erb
  app/views/items/show.html.erb
  config/routes.rb
  db/seeds.rb
Labels: enhancement

#35 Active storage
  app/assets/javascripts/business_photos.coffee
  app/assets/javascripts/item_photos.coffee
  app/assets/stylesheets/business_photos.scss
  app/assets/stylesheets/item_photos.scss
  app/controllers/business_photos_controller.rb
  app/controllers/item_photos_controller.rb
  app/helpers/business_photos_helper.rb
  app/helpers/item_photos_helper.rb
  app/models/business.rb
  app/models/item.rb
  app/views/businesses/edit.html.erb
  app/views/businesses/show.html.erb
  app/views/items/show.html.erb
  config/routes.rb
  db/migrate/20200909214144_create_active_storage_tables.active_storage.rb
  db/schema.rb
  test/controllers/business_photos_controller_test.rb
  test/controllers/item_photos_controller_test.rb
Labels: enhancement

#37 Customers controller To Mailer
  app/assets/javascripts/business_follows.coffee
  app/assets/stylesheets/business_follows.scss
  app/controllers/business_follows_controller.rb
  app/helpers/business_follows_helper.rb
  app/mailers/customer_mailer.rb
  app/models/business_follow.rb
  app/models/customer.rb
  app/models/owner.rb
  app/views/businesses/index.html.erb
  app/views/businesses/show.html.erb
  app/views/customer_mailer/welcome_email.html.erb
  app/views/customers/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20200910085824_add_first_and_last_name_to_customers.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/business_follows_controller_test.rb
  test/mailers/customer_mailer_test.rb
  test/mailers/previews/customer_mailer_preview.rb
Labels: enhancement

#36 Happy price initial
  Gemfile
  Gemfile.lock
  app/assets/javascripts/happy_codes.coffee
  app/assets/javascripts/happy_prices.coffee
  app/assets/stylesheets/happy_codes.scss
  app/assets/stylesheets/happy_prices.scss
  app/controllers/happy_codes_controller.rb
  app/controllers/happy_prices_controller.rb
  app/helpers/happy_codes_helper.rb
  app/helpers/happy_prices_helper.rb
  app/models/happy_price.rb
  app/models/item.rb
  app/views/happy_prices/_form.html.erb
  app/views/happy_prices/new.html.erb
  app/views/items/_item.html.erb
  app/views/items/show.html.erb
  config/application.rb
  config/routes.rb
  db/seeds.rb
  test/controllers/happy_codes_controller_test.rb
  test/controllers/happy_prices_controller_test.rb
Labels: enhancement

#38 Active storage
  .gitignore
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/storage.yml
Labels: enhancement

#40 Owner can see upcoming happy minutes and edit happy minutes
  app/controllers/happy_prices_controller.rb
  app/models/happy_price.rb
  app/models/item.rb
  app/views/happy_prices/edit.html.erb
  app/views/items/_item.html.erb
  app/views/items/show.html.erb
  config/routes.rb
Labels: enhancement

#41 First improve of the current navbar
  app/assets/images/Salle_1.jpg
  app/assets/stylesheets/happy_styles.css
  app/views/shared/_navbar.html.erb
Labels: enhancement

#42 Very first version of README
  README.md
Labels: documentation, enhancement

#45 field photo as a string removed form database
  app/controllers/businesses_controller.rb
  app/controllers/items_controller.rb
  app/dashboards/business_dashboard.rb
  app/dashboards/item_dashboard.rb
  app/views/businesses/index.html.erb
  db/migrate/20200907202645_create_businesses.rb
  db/migrate/20200907211107_create_items.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#43 Update business show
  .gitignore
  app/assets/images/.DS_Store
  app/assets/images/burger.png
  app/assets/stylesheets/happy_styles.css
  app/views/businesses/index.html.erb
  app/views/businesses/show.html.erb
  public/.DS_Store
  public/img/.DS_Store
  public/img/features/.DS_Store
  public/img/portfolio/.DS_Store
Labels: enhancement

#47 Fix picture in customer profile
  app/views/customers/show.html.erb
Labels: bug

#46 Happy codes initial
  app/controllers/happy_codes_controller.rb
  app/models/customer.rb
  app/models/happy_price.rb
  app/views/items/_item.html.erb
  app/views/items/show.html.erb
  config/routes.rb
Labels: enhancement

#49 Remove the field photo in the business creation form (for owners) and…
  app/views/businesses/create.html.erb
  app/views/businesses/new.html.erb
Labels: bug

#52 First simple email to notify followers
  app/mailers/customer_mailer.rb
  app/models/happy_price.rb
  app/views/customer_mailer/notify_followers_email.html.erb
Labels: enhancement

#44 Checking validations security
  .vscode/settings.json
  app/controllers/business_follows_controller.rb
  app/controllers/business_photos_controller.rb
  app/controllers/businesses_controller.rb
  app/controllers/customers_controller.rb
  app/controllers/happy_prices_controller.rb
  app/controllers/item_photos_controller.rb
  app/controllers/items_controller.rb
  app/controllers/owners_controller.rb
  app/models/administrator.rb
  app/models/business.rb
  app/models/business_follow.rb
  app/models/happy_price.rb
  app/models/item.rb
  app/views/businesses/index.html.erb
  app/views/businesses/show.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/items/show.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#58 some changes to front: front of owner profile page, colors of form te…
  app/assets/stylesheets/happy_colors.css
  app/assets/stylesheets/happy_styles.scss
  app/views/businesses/edit.html.erb
  app/views/businesses/new.html.erb
  app/views/businesses/show.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/items/_form.html.erb
  app/views/items/show.html.erb
  app/views/owners/show.html.erb
  app/views/static_pages/crystal_template.html.erb
  app/views/static_pages/kit_ui.html.erb
Labels: enhancement

#60 update route.rb
  config/routes.rb
Labels: bug

#61 buton 'back' changed in a devise form
  app/views/devise/registrations/edit.html.erb
Labels: bug

#62 fix bugs mvp: rescue error photos, max-width business photos
  app/assets/stylesheets/happy_colors.css
  app/assets/stylesheets/happy_styles.scss
  app/controllers/business_photos_controller.rb
  app/controllers/item_photos_controller.rb
  app/views/businesses/show.html.erb
  app/views/items/edit.html.erb
  app/views/items/show.html.erb
Labels: bug

#64 Adding Feature Item Category
  app/models/category.rb
  app/models/item.rb
  db/migrate/20200914121951_create_categories.rb
  db/migrate/20200914123504_remove_category_from_item.rb
  db/migrate/20200914123923_add_position_to_item.rb
  db/migrate/20200914134508_add_category_to_item.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/categories.yml
  test/models/category_test.rb
Labels: enhancement

#65 Feature adding item tag
  app/models/item.rb
  app/models/item_tag.rb
  app/models/tag.rb
  db/migrate/20200914145158_create_tags.rb
  db/migrate/20200914145322_create_item_tags.rb
  db/migrate/20200914150705_add_tag_to_item.rb
  db/schema.rb
  test/fixtures/item_tags.yml
  test/fixtures/tags.yml
  test/models/item_tag_test.rb
  test/models/tag_test.rb
Labels: enhancement

#69 Website marketing valorisation
  app/assets/stylesheets/happy_styles.scss
  app/views/shared/_navbar.html.erb
Labels: enhancement

#71 Add menu feature
  app/assets/javascripts/menu_items.coffee
  app/assets/javascripts/menus.coffee
  app/assets/stylesheets/menu_items.scss
  app/assets/stylesheets/menus.scss
  app/controllers/happy_codes_controller.rb
  app/controllers/menu_items_controller.rb
  app/controllers/menus_controller.rb
  app/helpers/menu_items_helper.rb
  app/helpers/menus_helper.rb
  app/models/business.rb
  app/models/menu.rb
  app/models/menu_item.rb
  app/views/businesses/show.html.erb
  app/views/items/index.html.erb
  app/views/items/show.html.erb
  app/views/menus/_form.html.erb
  app/views/menus/edit.html.erb
  app/views/menus/new.html.erb
  app/views/menus/show.html.erb
  config/routes.rb
  db/migrate/20200914115113_create_menus.rb
  db/migrate/20200914115322_create_menu_items.rb
  db/schema.rb
  test/controllers/menu_items_controller_test.rb
  test/controllers/menus_controller_test.rb
  test/fixtures/menu_items.yml
  test/fixtures/menus.yml
  test/models/menu_item_test.rb
  test/models/menu_test.rb
Labels: enhancement

#72 Categories form edition
  app/controllers/items_controller.rb
  app/views/items/_form.html.erb
Labels: enhancement

#78 Modify business show
  app/views/businesses/show.html.erb
Labels: enhancement

#77 Navigation cancel addition
  app/views/items/_category.html.erb
  app/views/items/_form.html.erb
  app/views/items/_item.html.erb
Labels: enhancement

#80 Improve user experience
  app/controllers/businesses_controller.rb
  app/controllers/happy_prices_controller.rb
  app/views/happy_prices/index.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: enhancement

#83 Modify business show
  app/controllers/businesses_controller.rb
  app/views/businesses/show.html.erb
Labels: enhancement

#82 Bug password confirmation devise
  app/controllers/application_controller.rb
  app/models/customer.rb
  app/models/owner.rb
  app/views/devise/registrations/new.html.erb
  config/locales/devise.fr.yml
Labels: enhancement

#84 Add form tags
  app/assets/javascripts/item_tags.coffee
  app/assets/stylesheets/happy_colors.css
  app/assets/stylesheets/item_tags.scss
  app/controllers/item_tags_controller.rb
  app/controllers/items_controller.rb
  app/helpers/item_tags_helper.rb
  app/models/item_tag.rb
  app/views/items/edit.html.erb
  app/views/items/index.html.erb
  app/views/menus/edit.html.erb
  config/routes.rb
  test/controllers/item_tags_controller_test.rb
Labels: enhancement

#86 Improve mailer and messages
  app/mailers/customer_mailer.rb
  app/mailers/owner_mailer.rb
  app/models/happy_price.rb
  app/views/customer_mailer/notify_followers_email.html.erb
  app/views/customer_mailer/welcome_email.html.erb
  app/views/owner_mailer/welcome_email.html.erb
Labels: enhancement

#85 Correction features roman
  app/views/items/_item.html.erb
  app/views/items/show.html.erb
  app/views/shared/_alerts.html.erb
Labels: bug, enhancement

#87 Rescue email sending
  Gemfile
  Gemfile.lock
  app/controllers/businesses_controller.rb
  app/models/customer.rb
  app/models/happy_price.rb
  app/models/owner.rb
  config/environments/development.rb
  config/initializers/truemail.rb
Labels: bug

#92 Fix happy prices index view
  app/views/happy_prices/index.html.erb
Labels: bug

#93 Validate happy price
  app/controllers/happy_prices_controller.rb
  app/models/happy_price.rb
Labels: enhancement

#95 Designing owner profile
  app/assets/stylesheets/happy_colors.css
  app/controllers/businesses_controller.rb
  app/views/businesses/new.html.erb
  app/views/owners/show.html.erb
  app/views/shared/_footer.html.erb
Labels: enhancement

#98 tel link
  app/views/businesses/show.html.erb
Labels: bug

#99 Fix errors edit
  app/controllers/items_controller.rb
  app/controllers/menus_controller.rb
  app/models/business.rb
  app/models/menu.rb
  app/views/businesses/show.html.erb
  app/views/happy_prices/index.html.erb
Labels: bug

#101 Indent : Using auto indent from VS Code
  app/controllers/business_follows_controller.rb
  app/controllers/business_photos_controller.rb
  app/controllers/customers_controller.rb
  app/controllers/item_photos_controller.rb
  app/controllers/owners_controller.rb
  app/controllers/static_pages_controller.rb
  app/models/business_follow.rb
  app/models/customer.rb
  app/models/owner.rb
  app/views/businesses/edit.html.erb
  app/views/businesses/index.html.erb
  app/views/businesses/show.html.erb
  app/views/customer_mailer/notify_followers_email.html.erb
  app/views/customer_mailer/welcome_email.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/happy_prices/index.html.erb
  app/views/items/_category.html.erb
  app/views/items/_item.html.erb
  app/views/items/edit.html.erb
  app/views/items/index.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/crystal.html.erb
  app/views/menus/_form.html.erb
  app/views/menus/edit.html.erb
  app/views/menus/new.html.erb
  app/views/menus/show.html.erb
  app/views/owner_mailer/welcome_email.html.erb
  app/views/static_pages/home.html.erb
  app/views/static_pages/kit_ui.html.erb
Labels: enhancement

#104 Timer happy price edition
  app/assets/stylesheets/happy_colors.css
  app/views/businesses/show.html.erb
  app/views/happy_prices/index.html.erb
  app/views/items/_category.html.erb
  app/views/items/_item.html.erb
Labels: enhancement

#105 Add confirm messages before delete and in business show set "Modify" instead of "sign_in" for owners
  app/views/businesses/show.html.erb
  app/views/happy_prices/index.html.erb
  app/views/menus/edit.html.erb
  app/views/menus/show.html.erb
Labels: bug

#110 Fix name prices become minutes
  app/views/businesses/index.html.erb
  app/views/businesses/show.html.erb
  app/views/happy_prices/index.html.erb
  app/views/shared/_navbar.html.erb
Labels: bug
